import cv2 as cv
import face_recognition
import pickle
import os

#Importing images of students
imagesPath="Images"
imgPathList=os.listdir(imagesPath)
imgList=[]
studentId=[]

for path in imgPathList:
    imgList.append(cv.imread(os.path.join(imagesPath,path)))
    #Splits the path name with extension and file name and only to append first element we used [0]
    studentId.append(os.path.splitext(path)[0])
    
#Function to generate encoding
#Gives a list of all the encodings

def makeencodings(imgList):
    encodingList=[]
    for img in imgList:
        #As face_recognition library uses rgb adn opencv bgr
        img=cv.cvtColor(img,cv.COLOR_BGR2RGB)
        encoding=face_recognition.face_encodings(img)[0]    

        #The [0] in the last line of the code snippet is used to access the first (and usually the only) face encoding generated by the face_recognition.face_encodings(img) function.
        #The face_recognition library's face_encodings function returns a list of face encodings found in the input image. However, in your case, you seem to be assuming that there is only one face in each image, and you are interested in the encoding of that specific face.
        
        encodingList.append(encoding)
        
    return encodingList

print("!! ENCODING BEGINS !!")
encodeList=makeencodings(imgList)
print("!! ENCODING COMPLETE !!")

#Save in file encoding with id so which id corresponds to which image to easily recognize
encodeListWithId=[encodeList,studentId]

file1=open("EncodeFile.p","wb")
pickle.dump(encodeListWithId,file1)

file1.close()
print("File Saved")